openapi: 3.0.0
info:
  description: This is a simple description for the App API.
  version: 1.0.0
  title: App API
  contact:
    email: phoenix-api@it4sport.de
  
paths: 
  /login:
    post:
      tags:
        - Login
      summary: login into the app
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginData'
      responses: 
        '200':
          description: 'successfull'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
        '400':
          description: 'Missing Data'
        '401':
          description: 'Either Authorization information is missing or invalid, or more than one user are found. This feature is not implemented yet.'
          
  /startpass:
    get:
      tags:
        - Startpass
      summary: getting the startpass
      security:
        - bearerAuth: []
      responses: 
        '200':
          description: 'successfull'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Startpass'
        '401':
          description: 'Token invalid'
        '404':
          description: 'Startpass not found, there is no startpass for this sport or invalid uuid.'
  /user:
    get:
      tags:
        - User
      summary: getting the user data
      security:
        - bearerAuth: []
      responses: 
        '200':
          description: 'successfull'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: 'Token invalid'
  /user/photo:
    get:
      tags:
        - Passbild
      summary: getting the pass image
      security:
        - bearerAuth: []
      responses: 
        '200':
          description: 'successfull'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Passbild'
        '401':
          description: 'Token invalid'
    post:
      tags:
        - Passbild
      summary: uploading the pass image
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Image'
      security:
        - bearerAuth: []
      responses: 
        '200':
          description: 'successfull'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Passbild'
        '400':
          description: 'Image invalid or missing.'
        '401':
          description: 'Token invalid'
        '403':
          description: 'Photo upload only available for Triathlon or photo upload locked'
servers:
  - url: 'https://api.it4sport.de/api/app'
  
components:
  schemas:
    Login:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: "DDFB67A9-200F-4A9E-B6BA-E31C54037B2C"
              description: id of the person
            firstname:
              type: string
              example: "Max"
              description: first name of the person
            lastname:
              type: string
              example: "Mustermann"
              description: last name of the person
            sex:
              type: integer
              example: 1
              description: number of the sex of the person
            anrede:
              type: object
              properties:
                anredeNr: 
                  type: string
                  example: "1"
                  description: number of the form of address as a string
                anredeKopf:
                  type: string
                  example: "Herrn"
                  description: form of address declinated
                anrede: 
                  type: string
                  example: "Herr"
                  description: basic form of address
                anredeFormel:
                  type: string
                  example: "Sehr geehrter Herr"
                  description: form of address as an sentence begin
                anredeSort:
                  type: string
                  example: "A"
                  description: a
                nMandant:
                  type: string
                  example: "100"
                  description: a
                cSportart:
                  type: string
                  example: "ta"
                  description: kind of sport of the person as an abbreviation
                dtModZeit:
                  type: string
                  pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}$
                  example: "2012-11-02 15:11:15.114"
                  description: date and time of data modification
                uModPerson:
                  type: string
                  format: uuid
                  example: "DDFB67A9-4A9E-200F-B6BA-E31C54037B2C"
                  description: id of the person that modyfied the data
                uID:
                  type: string
                  format: uuid
                  example: "DDFB67A9-B6BA-46F9-B66D-4B84A7795E99"
                textfeldNV:
                  type: string
                anredeFormat:
                  type: string
                  example: "111"
                anredeDefault:
                  type: string
                  description: default form of address
            birthday:
              type: string
              format: date
              example: "21-08-1980"
              description: birth date of the person
            mandant:
              type: object
              properties:
                id:
                  type: integer
                  example: 100
                  description: mandant id
                name:
                  type: string
                  example: "Deutsche Triathlon Union"
                  description: name of the mandant
                shortName:
                  type: string
                  example: "DTU"
                  description: abbreviation of the name
                alternativeName:
                  type: string
                  description: alternative name (most of the time null)
                sportsType:
                  type: string
                  example: "ta"
                  description: abbreviation of the sport
            token:
              type: string
              example: "wVnUkLwmZxKPKgHnTRrlHzvX4tjZB7xVoPRgnMaN"
              description: login token
    Startpass:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: "D8AD313F-AB3B-482C-4039-9A2A16F1C9D1"
            licenseStart:
              type: string
              format: date
              example: "2022-05-09"
              description: license start date
            licenseEnd:
              type: string
              format: date
              example: "2022-12-31"
              description: license end date
            status:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  example: "D8AD313F-AB3B-482C-4039-9A2A16F1C9D1"
                  description: status id
                number:
                  type: string
                  example: "7"
                  description: status number as string
                name:
                  type: string
                  example: "Startpassabmeldung eingegangen"
                  description: name of the status
                short:
                  type: string
                  example: "SE"
                  description: abbreviation of the status name
                description:
                  type: string
                  example: "Der Startpass wurde abgemeldet."
                  description: the description of the status
            club:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  example: "D8AD313F-AB3B-482C-4039-9A2A16F1C9D1"
                  description: club id
                number:
                  type: string
                  example: "80002"
                  description: club number
                name:
                  type: string
                  example: "Team Team"
                  description: team name
                shortName:
                  type: string
                  example: "TT"
                  description: abbreviation of the team name
                city:
                  type: string
                  example: "Fellbach"
                  description: city of club
                postal:
                  type: string
                  example: "70736"
                  description: postal code of city of the club
                joiningDate:
                  type: string
                  format: date
                  example: "2011-01-01"
                  description: date of joining the club
                leavingDate:
                  type: string
                  format: date
                  example: "2012-01-01"
                  description: date of leaving the club
                latitude:
                  type: number
                  format: double
                  example: 48.236210499999997
                  description: latitude of location
                lonigtude:
                  type: number
                  format: double
                  example: 11.536210499999997
                  description: longitude of location
                foundingYear:
                  type: string
                  pattern: ^[0-9]{4}$
                  example: "2000"
                  description: founding year of club
                sectionFoundingYear:
                  type: string
                www:
                  type: string
                  example: "https://de.club.de/team"
                  description: club homepage
                updatedAt:
                  type: string
                  format: date-time
                  example: "2022-05-03T11:09:42+02:00"
            person:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  example: "DDFB67A9-200F-4A9E-B6BA-E31C54037B2C"
                  description: id of the person
                firstname:
                  type: string
                  example: "Max"
                  description: first name of the person
                lastname:
                  type: string
                  example: "Mustermann"
                  description: last name of the person
                sex:
                  type: integer
                  example: 1
                  description: number of the sex of the person
                anrede:
                  type: object
                  properties:
                    anredeNr: 
                      type: string
                      example: "1"
                      description: number of the form of address as a string
                    anredeKopf:
                      type: string
                      example: "Herrn"
                      description: form of address declinated
                    anrede: 
                      type: string
                      example: "Herr"
                      description: basic form of address
                    anredeFormel:
                      type: string
                      example: "Sehr geehrter Herr"
                      description: form of address as an sentence begin
                    anredeSort:
                      type: string
                      example: "A"
                      description: a
                    nMandant:
                      type: string
                      example: "100"
                      description: a
                    cSportart:
                      type: string
                      example: "ta"
                      description: kind of sport of the person as an abbreviation
                    dtModZeit:
                      type: string
                      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}$
                      example: "2012-11-02 15:11:15.114"
                      description: date and time of data modification
                    uModPerson:
                      type: string
                      format: uuid
                      example: "DDFB67A9-4A9E-200F-B6BA-E31C54037B2C"
                      description: id of the person that modyfied the data
                    uID:
                      type: string
                      format: uuid
                      example: "DDFB67A9-B6BA-46F9-B66D-4B84A7795E99"
                    textfeldNV:
                      type: string
                    anredeFormat:
                      type: string
                      example: "111"
                    anredeDefault:
                      type: string
                      description: default form of address
                birthday:
                  type: string
                  format: date
                  example: "21-08-1980"
                  description: birth date of the person
                mandant:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 100
                      description: mandant id
                    name:
                      type: string
                      example: "Deutsche Triathlon Union"
                      description: name of the mandant
                    shortName:
                      type: string
                      example: "DTU"
                      description: abbreviation of the name
                    alternativeName:
                      type: string
                      description: alternative name (most of the time null)
                    sportsType:
                      type: string
                      example: "ta"
                      description: abbreviation of the sport
            qrcode:
              type: string
              description: string version of the qr code
            abgemeldet:
              type: string
              format: date
              example: "2010-01-01"
              description: date of signing out
            updatedAt:
              type: string
              format: date
              example: "2010-01-01"
              description: date of last update
            passNrTa:
              type: string
              example: 00-80002-0012705-1980"
            passPremium:
              type: string
              example: "PR"
    User:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: string
              format: uuid
              example: "A3DE9D67-5EAA-4AB5-9E8F-3D1CA03F5562"
              description: id of the user
            firstname:
              type: string
              example: "Max"
              description: first name of user
            lastname:
              type: string
              example: "Max"
              description: last name of user
            sex:
              type: integer
              example: 1
              description: sex of user as a number
            anrede:
              type: object
              properties:
                anredeNr:
                  type: string
                  example: "1"
                  description: number of form of address as a string
                anredeKopf:
                  type: string
                  example: "Herrn"
                  description: specific form of address
                anrede:
                  type: string
                  example: "Herr"
                  description: standart form of address
                anredeFormel:
                  type: string
                  example: "Sehr geehrter Herr"
                  description: form of address as a beginning of a sentence
                anredeSort:
                  type: string
                  example: "A"
                nMandant:
                  type: string
                  example: "100"
                cSportart:
                  type: string
                  example: "ta"
                  description: sport of user as an abbreviation
                dtModZeit:
                  type: string
                  pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}$
                  example: "2012-11-02 18:11:15.710"
                  description: date and time of last data modification
                uModPerson:
                  type: string
                  description: last modifier of data
                uID:
                  type: string
                  format: uuid
                  example: "C7239978-788D-46F9-B66D-4B84A7795E99"
                  description: id of the person
                textfeldNV:
                  type: string
                anredeFormat:
                  type: string
                  example: "111"
                  description: format of form of address
                anredeDefault:
                  type: string
                  description: default form of address
            birthday:
              type: string
              format: date
              example: "2000-01-01"
              description: date of birth of user
            mandant:
              type: object
              properties:
                id:
                  type: integer
                  example: 100
                  description: id of mandant as integer
                name:
                  type: string
                  example: "Deutsche Triathlon Union"
                  description: name of the mandant
                shortName:
                  type: string
                  example: "DTU"
                  description: name of the mandant as an abbreviation
                alternativeName:
                  type: string
                  description: alternative name of mandant if available
                sportsType:
                  type: string
                  example: "ta"
                  description: sports type of mandant as an abbreviation
    Passbild:
      type: object
      properties:
        img:
          type: string
          example: "data:image/jpg;base64,..."
          description: pass image coded in base64
        isEditable:
          type: boolean
          example: true
          description: boolean value set true if pass image is editable
          
    LoginData:
      type: object
      properties:
        username:
          type: string
          example: "username123"
        passsord:
          type: string
          example: "12345678"
        device_name:
          type: string
          example: "device"
    Image:
      type: string
      example: "data:image/jpg;base64,..."
      
    Login400Message:
      type: string
      
    
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer